#!/bin/bash


for j in ICI_004 ICI_005 ICI_006 ICI_007 ICI_008 ICI_009 ICI_010 ICI_011 ICI_012; do
echo "RUN: 1"
echo "Dataset: " $j
nvols=`fslnvols /Users/Leelab/Documents/Imaging/Item_context_interference/raw/${j}/${j}_Run1.nii`
echo "Volumes: " $nvols

cat /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/ICI_001/ICI_001_Run1.feat/design.fsf|sed "s/ICI_001/${j}/g" |sed "s/300/$nvols/g">/Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf ;
cd /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j};
feat /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf;
mv  /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf ~/.Trash/;

done

for j in ICI_004 ICI_005 ICI_006 ICI_007 ICI_008 ICI_009 ICI_010 ICI_011 ICI_012; do

echo "RUN: 2"
echo "Dataset: " $j
nvols=`fslnvols /Users/Leelab/Documents/Imaging/Item_context_interference/raw/${j}/${j}_Run2.nii`
echo "Volumes: " $nvols

cat /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/ICI_001/ICI_001_Run2.feat/design.fsf|sed "s/ICI_001/${j}/g" |sed "s/300/$nvols/g">/Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf ;
cd /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j};
feat /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf;
mv  /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf ~/.Trash/;

done

for j in ICI_004 ICI_005 ICI_006 ICI_007 ICI_008 ICI_009 ICI_010 ICI_011 ICI_012; do

echo "RUN: 3"
echo "Dataset: " $j
nvols=`fslnvols /Users/Leelab/Documents/Imaging/Item_context_interference/raw/${j}/${j}_Run3.nii`
echo "Volumes: " $nvols

cat /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/ICI_001/ICI_001_Run3.feat/design.fsf|sed "s/ICI_001/${j}/g" |sed "s/300/$nvols/g">/Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf ;
cd /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j};
feat /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf;
mv  /Users/Leelab/Documents/Imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf ~/.Trash/;

done

	
	
