#!/bin/bash


for j in ICI_002 ICI_003 ICI_004 ICI_005 ICI_006 ICI_007 ICI_008 ICI_009 ICI_010 ICI_012;  do


echo "Dataset: " $j 
echo "Scan: " 1
nvols=`fslnvols /Users/Leelab/Documents/imaging/Item_context_interference/analysis/${j}/${j}_Run1.feat/filtered_func_data.nii.gz`
echo "Volumes: " $nvols
echo "Scan: " 2
nvols=`fslnvols /Users/Leelab/Documents/imaging/Item_context_interference/analysis/${j}/${j}_Run2.feat/filtered_func_data.nii.gz`
echo "Volumes: " $nvols
echo "Scan: " 3
nvols=`fslnvols /Users/Leelab/Documents/imaging/Item_context_interference/analysis/${j}/${j}_Run3.feat/filtered_func_data.nii.gz`
echo "Volumes: " $nvols


cat /Users/Leelab/Documents/imaging/Item_context_interference/analysis/ICI_001/ICI_001_fixed.gfeat/design.fsf|sed "s/ICI_001/${j}/g">/Users/Leelab/Documents/imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf ;
cd /Users/Leelab/Documents/imaging/Item_context_interference/analysis/${j}/;
feat /Users/Leelab/Documents/imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf;
mv  /Users/Leelab/Documents/imaging/Item_context_interference/analysis/${j}/tmp_s${j}.fsf ~/.Trash/;

done



