#!/bin/bash

for j in ICI_001 ICI_002 ICI_003 ICI_004 ICI_005 ICI_006 ICI_007 ICI_008 ICI_009 ICI_010 ICI_011 ICI_012;  do

	for i in 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156; do #cope number
	
		for n in prc_bin; do #name of mask
				
echo "${j} cope${i} mask${n}_peak"

featquery 1 ~/Documents/Imaging/Item_context_interference/analysis/${j}/${j}_fixed_denoised.gfeat/cope${i}.feat 1 stats/pe1 ${n}_peak_HW -p -s ~/Documents/${n}.nii -mm -26 -8 -42


done
	done
		done
		
		
	
		

